version: '3.3'

services:
  nginx:
    image: openresty/openresty:alpine
    restart: always
    ports:
      - "3000:443"
    volumes:
      - ./nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./nginx/conf/.htpasswd:/usr/local/openresty/nginx/conf/.htpasswd
      - ./nginx/ssl/:/etc/ssl/
#      - ./nginx/flex/:/var/www/flex/
      - flex_ui:/var/www/flex/
    networks:
      - flex_network
    depends_on:
      - flex-api
      - flex-ui

  flex-api:
    image: ${DOCKER_REGISTRY}/flexapi:latest
    restart: always
    ports:
      - "8881:8080"
    volumes:
      - ./flex-api/conf/:/etc/flex/
      - flex_logs:/var/log/flex
    networks:
      - flex_network
    depends_on:
      - postgres-db

  flex-ui:
    image: ${DOCKER_REGISTRY}/flexui
    volumes:
      - flex_ui:/var/www/

  postgres-db:
      image: postgres:alpine
      restart: always
      environment:
        POSTGRES_PASSWORD: flexMasterPassw0rd
      ports:
        - "5432:5432"
      volumes:
        - ./postgres-db/scripts/test/create_flex_schema.sql:/docker-entrypoint-initdb.d/create_flex_schema.sql
        - postgres_database:/var/lib/postgresql/data
      networks:
        - flex_network

networks:
  flex_network:
    driver: bridge

volumes:
  flex_logs:
  postgres_database:
  flex_ui:
