version: '3.3'

services:
  nginx:
      build: ./nginx
      restart: always
      ports:
        - "80:80"
        - "443:443"
      networks:
        - flex_network
      depends_on:
        - flex-api

  flex-api:
    build: ./flex-api
    restart: always
    ports:
      - "8881:8080"
    volumes:
      - flex_logs:/var/log/flex
    networks:
      - flex_network

  postgres-db:
    build: ./postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: flexProdMasterPassw0rd_231
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data
    networks:
      - flex_network

networks:
  flex_network:
    driver: bridge

volumes:
  flex_logs:
  postgres_database:
